---
resources:
- name: configuration
  type: git
  source:
    uri: git@github.com:p-ssanders/simple-pipelines.git
    private_key: ((git-deploy-key.private_key))
    branch: master

- name: terraform-image
  type: docker-image
  source:
    repository: hashicorp/terraform
    tag: 0.11.14

- name: daily-trigger
  type: time
  source:
    interval: 24h

jobs:
- name: pave-iaas
  plan:
  - aggregate:
    - get: configuration
    - get: terraform-image
    - get: daily-trigger
      trigger: true
  - task: terraform-apply
    image: terraform-image
    file: configuration/tasks/terraform-apply.yml
    input_mapping:
      configuration: configuration
    params:
      CONFIG_DIR: sandbox/terraform/terraforming-pks
      TF_VAR_access_key: ((access_key_id))
      TF_VAR_secret_key: ((secret_access_key))
      TF_VAR_ssl_cert: ((lets_encrypt_cert.certificate))
      TF_VAR_ssl_private_key: ((lets_encrypt_cert.private_key))
