---
platform: linux
inputs:
- name: env
params:
  ENV_FILE:
  CERTIFICATE_PEM:
  PRIVATE_KEY_PEM:
run:
  path: bash
  args:
    - "-c"
    - |
      om --env env/"${ENV_FILE}" update-ssl-certificate \
      --certificate-pem "$CERTIFICATE_PEM" \
      --private-key-pem "$PRIVATE_KEY_PEM"