---
platform: linux
params:
  RDS_ADDRESS:
  RDS_PORT:
  RDS_USERNAME:
  RDS_PASSWORD:
  OPS_MANAGER_HOST:
  OPS_MANAGER_SSH_PRIVATE_KEY:
run:
  path: sh
  args:
  - "-c"
  - |
    mkdir ~/.ssh
    ssh-keyscan -H "${OPS_MANAGER_HOST}" >> ~/.ssh/known_hosts

    echo "${OPS_MANAGER_SSH_PRIVATE_KEY}" > ssh-private-key
    chmod 0400 ssh-private-key

    ssh -T -i ssh-private-key ubuntu@"${OPS_MANAGER_HOST}" << EOF
      mysql \
      --host="${RDS_ADDRESS}" \
      --port="${RDS_PORT}" \
      --user="${RDS_USERNAME}" \
      --password="${RDS_PASSWORD}" \
      --execute="create database if not exists bosh;"
    EOF
