---
platform: linux
params:
  RDS_ADDRESS:
  RDS_PORT:
  RDS_USERNAME:
  RDS_PASSWORD:
run:
  path: sh
  args:
  - "-c"
  - |

    set -x

    mysql \
    --host="${RDS_ADDRESS}" \
    --port="${RDS_PORT}" \
    --user="${RDS_USERNAME}" \
    --password="${RDS_PASSWORD}" \
    --execute="create database bosh;"
