---
resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: platform-automation-pivnet
  type: pivnet
  source:
    api_token: ((pivnet-api-token))
    product_slug: platform-automation
    product_version: 3\.0
    sort_by: semver

- name: platform-automation-image
  type: s3
  source:
    access_key_id: ((access_key_id))
    secret_access_key: ((secret_access_key))
    region: us-east-1
    bucket: com.fionathebluepittie.sandbox
    regexp: platform-automation/platform-automation-image-(.*).tgz

- name: platform-automation-tasks
  type: s3
  source:
    access_key_id: ((access_key_id))
    secret_access_key: ((secret_access_key))
    region: us-east-1
    bucket: com.fionathebluepittie.sandbox
    regexp: platform-automation/platform-automation-tasks-(.*).zip

- name: daily-trigger
  type: time
  source:
    interval: 24h

jobs:
- name: fetch-platform-automation
  plan:
  - get: daily-trigger
    trigger: true
  - get: platform-automation-pivnet
  - aggregate:
    - put: platform-automation-image
      params:
        file: platform-automation-pivnet/*image*.tgz
    - put: platform-automation-tasks
      params:
        file: platform-automation-pivnet/*tasks*.zip