---
resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: configuration
  type: git
  source:
    uri: git@github.com:pivotal-samuel-sanders/simple-pipelines.git
    private_key: ((git-deploy-key.private_key))
    branch: master

- name: platform-automation-pivnet
  type: pivnet
  source:
    api_token: ((pivnet-api-token))
    product_slug: platform-automation
    product_version: 3\.0
    sort_by: semver

- name: platform-automation-image
  type: s3
  source:
    access_key_id: ((access_key_id))
    secret_access_key: ((secret_access_key))
    region: us-east-1
    bucket: com.fionathebluepittie.sandbox
    regexp: platform-automation/platform-automation-image-(.*).tgz

- name: platform-automation-tasks
  type: s3
  source:
    access_key_id: ((access_key_id))
    secret_access_key: ((secret_access_key))
    region: us-east-1
    bucket: com.fionathebluepittie.sandbox
    regexp: platform-automation/platform-automation-tasks-(.*).zip

- name: ops-manager-backup
  type: s3
  source:
    access_key_id: ((access_key_id))
    secret_access_key: ((secret_access_key))
    region: us-east-1
    bucket: com.fionathebluepittie.sandbox
    regexp: ops-manager/installation-(.*).zip

jobs:
- name: fetch-platform-automation
  plan:
  - get: platform-automation-pivnet
    trigger: true
  - aggregate:
    - put: platform-automation-image
      params:
        file: platform-automation-pivnet/*image*.tgz
    - put: platform-automation-tasks
      params:
        file: platform-automation-pivnet/*tasks*.zip

- name: install-ops-manager
  plan:
    - aggregate:
      - get: configuration
      - get: platform-automation-tasks
        passed:
        - fetch-platform-automation
        params:
          unpack: true
      - get: platform-automation-image
        passed:
        - fetch-platform-automation
        params:
          unpack: true
    - task: credhub-interpolate
      image: platform-automation-image
      file: platform-automation-tasks/tasks/credhub-interpolate.yml
      params:
        CREDHUB_CLIENT: ((credhub-client))
        CREDHUB_SECRET: ((credhub-secret))
        CREDHUB_SERVER: "https://credhub.control.fionathebluepittie.com:8844"
        CREDHUB_CA_CERT: ((lets_encrypt_cert.ca))
        PREFIX: /concourse/main/sandbox
        INTERPOLATION_PATHS: sandbox
      input_mapping:
        files: configuration
      output_mapping:
        interpolated-files: interpolated-config
    - task: download-product
      image: platform-automation-image
      file: platform-automation-tasks/tasks/download-product.yml
      params:
        CONFIG_FILE: sandbox/install-ops-manager/download-ops-manager.yml
      input_mapping:
        config: interpolated-config
    - task: create-vm
      image: platform-automation-image
      file: platform-automation-tasks/tasks/create-vm.yml
      params:
        OPSMAN_CONFIG_FILE: sandbox/install-ops-manager/configure-ops-manager.yml
        STATE_FILE: sandbox/state.yml
      input_mapping:
        image: downloaded-product
        config: interpolated-config
        state: interpolated-config
      ensure:
        do:
          - task: make-commit
            image: platform-automation-image
            file: platform-automation-tasks/tasks/make-git-commit.yml
            input_mapping:
              repository: configuration
              file-source: generated-state
            output_mapping:
              repository-commit: configuration-commit
            params:
              FILE_SOURCE_PATH: state.yml
              FILE_DESTINATION_PATH: sandbox/state.yml
              GIT_AUTHOR_EMAIL: "pipeline-bot@fionathebluepittie.com"
              GIT_AUTHOR_NAME: "Pipeline Bot"
              COMMIT_MESSAGE: "update ops manager state file"
          - put: configuration
            params:
              repository: configuration-commit
              merge: true
    - task: configure-authentication
      image: platform-automation-image
      file: platform-automation-tasks/tasks/configure-authentication.yml
      attempts: 3
      params:
        ENV_FILE: sandbox/env.yml
        AUTH_CONFIG_FILE: sandbox/install-ops-manager/auth.yml
      input_mapping:
        env: interpolated-config
        config: interpolated-config
    - task: configure-tls
      image: platform-automation-image
      params:
        ENV_FILE: sandbox/env.yml
        CERTIFICATE_PEM: |
          ((lets_encrypt_cert.certificate))
          ((lets_encrypt_cert.ca))
        PRIVATE_KEY_PEM: ((lets_encrypt_cert.private_key))
      input_mapping:
        env: interpolated-config
      config: # TODO migrate this to a file in tasks/
        platform: linux
        inputs:
        - name: env
        run:
          path: bash
          args:
            - "-c"
            - |
              om --env env/"${ENV_FILE}" update-ssl-certificate \
              --certificate-pem "$CERTIFICATE_PEM" \
              --private-key-pem "$PRIVATE_KEY_PEM"
    - task: create-bosh-director-database
      image: platform-automation-image
      file: configuration/tasks/create-bosh-database.yml
      params:
        RDS_ADDRESS: ((rds_address))
        RDS_PORT: ((rds_port))
        RDS_USERNAME: ((rds_username))
        RDS_PASSWORD: ((rds_password))
    - task: configure-bosh-director
      image: platform-automation-image
      file: platform-automation-tasks/tasks/configure-director.yml
      params:
        ENV_FILE: sandbox/env.yml
        DIRECTOR_CONFIG_FILE: sandbox/install-ops-manager/bosh-director.yml
        VARS_FILES: vars/sandbox/install-ops-manager/bosh-director-vars.yml
      input_mapping:
        env: interpolated-config
        config: interpolated-config
        vars: interpolated-config
    - task: apply-director-changes
      image: platform-automation-image
      file: platform-automation-tasks/tasks/apply-director-changes.yml
      params:
        ENV_FILE: sandbox/env.yml
      input_mapping:
        env: interpolated-config

- name: backup-ops-manager
  plan:
    - aggregate:
      - get: platform-automation-tasks
        params:
          unpack: true
      - get: platform-automation-image
        params:
          unpack: true
      - get: configuration
        passed:
        - install-ops-manager
        trigger: true
    - task: credhub-interpolate
      image: platform-automation-image
      file: platform-automation-tasks/tasks/credhub-interpolate.yml
      params:
        CREDHUB_CLIENT: ((credhub-client))
        CREDHUB_SECRET: ((credhub-secret))
        CREDHUB_SERVER: "https://credhub.control.fionathebluepittie.com:8844"
        CREDHUB_CA_CERT: ((lets_encrypt_cert.ca))
        PREFIX: /concourse/main/sandbox
        INTERPOLATION_PATHS: sandbox
      input_mapping:
        files: configuration
      output_mapping:
        interpolated-files: interpolated-config
    - task: backup-ops-manager
      image: platform-automation-image
      file: platform-automation-tasks/tasks/export-installation.yml
      params:
        ENV_FILE: sandbox/env.yml
        INSTALLATION_FILE: installation-$timestamp.zip
      input_mapping:
        env: interpolated-config
    - put: ops-manager-backup
      params:
        file: installation/installation-*.zip
