---
resources:
- name: configuration
  type: git
  source:
    uri: ((config-repo))
    private_key: ((git-deploy-key.private_key))
    branch: master

- name: platform-automation-tasks
  type: s3
  source:
    access_key_id: ((access_key_id))
    secret_access_key: ((secret_access_key))
    region: ((region))
    bucket: ((platform-automation-bucket))
    regexp: platform-automation/platform-automation-tasks-(.*).zip

- name: platform-automation-image
  type: s3
  source:
    access_key_id: ((access_key_id))
    secret_access_key: ((secret_access_key))
    region: ((region))
    bucket: ((platform-automation-bucket))
    regexp: platform-automation/platform-automation-image-(.*).tgz

- name: pks-product
  type: s3
  source:
    access_key_id: ((access_key_id))
    secret_access_key: ((secret_access_key))
    region: ((region))
    bucket: ((env-bucket))
    regexp: pks/products/(.*).pivotal

- name: pks-stemcell
  type: s3
  source:
    access_key_id: ((access_key_id))
    secret_access_key: ((secret_access_key))
    region: ((region))
    bucket: ((env-bucket))
    regexp: pks/stemcells/(.*).tgz

jobs:
- name: fetch-pks
  plan:
    - aggregate:
      - get: platform-automation-tasks
        params:
          unpack: true
      - get: platform-automation-image
        params:
          unpack: true
      - get: configuration
    - task: credhub-interpolate
      image: platform-automation-image
      file: platform-automation-tasks/tasks/credhub-interpolate.yml
      params:
        CREDHUB_CLIENT: ((credhub-client))
        CREDHUB_SECRET: ((credhub-secret))
        CREDHUB_SERVER: ((credhub-server))
        CREDHUB_CA_CERT: ((lets_encrypt_cert.ca))
        PREFIX: /concourse/main/sandbox
        INTERPOLATION_PATHS: sandbox/install-pks
      input_mapping:
        files: configuration
      output_mapping:
        interpolated-files: interpolated-config
    - task: download-pks-and-stemcell
      image: platform-automation-image
      file: platform-automation-tasks/tasks/download-product.yml
      params:
        CONFIG_FILE: sandbox/install-pks/pks.yml
      input_mapping:
        config: interpolated-config
      output_mapping:
        downloaded-product: pks-product
        downloaded-stemcell: pks-stemcell
    - aggregate:
      - put: pks-product
        params:
          file: downloaded-product/*.pivotal
      - put: pks-stemcell
        params:
          file: pks-stemcell/*.tgz
