---
resources:
- name: configuration
  type: git
  source:
    uri: git@github.com:pivotal-samuel-sanders/pcf-automation.git
    private_key: ((git-deploy-key.private_key))
    branch: master

- name: terraform-image
  type: docker-image
  source:
    repository: hashicorp/terraform
    tag: 0.11.14

- name: platform-automation-tasks
  type: s3
  source:
    access_key_id: ((access_key_id))
    secret_access_key: ((secret_access_key))
    region: us-east-1
    bucket: pcf.practice.platform-automation
    regexp: platform-automation/platform-automation-tasks-(.*).zip

- name: platform-automation-image
  type: s3
  source:
    access_key_id: ((access_key_id))
    secret_access_key: ((secret_access_key))
    region: us-east-1
    bucket: pcf.practice.platform-automation
    regexp: platform-automation/platform-automation-image-(.*).tgz

- name: pks-product
  type: s3
  source:
    access_key_id: ((access_key_id))
    secret_access_key: ((secret_access_key))
    region: us-east-1
    bucket: com.fionathebluepittie.sandbox
    regexp: pks/products/pivotal-container-service-(.*).pivotal

jobs:
- name: pave-iaas
  plan:
    - aggregate:
      - get: terraform-image
      - get: configuration
    - task: terraform-apply
      image: terraform-image
      file: configuration/tasks/terraform-apply.yml
      input_mapping:
        configuration: configuration
      params:
        CONFIG_DIR: terraform/terraforming-pks
        TF_VAR_access_key: ((access_key_id))
        TF_VAR_secret_key: ((secret_access_key))
        TF_VAR_ssl_cert: ((lets_encrypt_cert.certificate))
        TF_VAR_ssl_private_key: ((lets_encrypt_cert.private_key))

- name: download-pks
  plan:
    - aggregate:
      - get: platform-automation-tasks
        params:
          unpack: true
      - get: platform-automation-image
        params:
          unpack: true
      - get: configuration
    - task: credhub-interpolate
      image: platform-automation-image
      file: platform-automation-tasks/tasks/credhub-interpolate.yml
      params:
        CREDHUB_CLIENT: ((credhub-client))
        CREDHUB_SECRET: ((credhub-secret))
        CREDHUB_SERVER: "https://credhub.control.fionathebluepittie.com:8844"
        CREDHUB_CA_CERT: ((lets_encrypt_cert.ca))
        PREFIX: /concourse/main/sandbox
        INTERPOLATION_PATHS: sandbox
      input_mapping:
        files: configuration
      output_mapping:
        interpolated-files: interpolated-config
    - task: download-pks-and-stemcell
      image: platform-automation-image
      file: platform-automation-tasks/tasks/download-product.yml
      params:
        CONFIG_FILE: sandbox/install-pks/download-pks.yml
      input_mapping:
        config: interpolated-config
    - aggregate:
      - put: pks-product
        params:
          file: downloaded-product/pivotal-container-service-*.pivotal

- name: upload-and-stage-pks
  plan:
    - get: platform-automation-tasks
      params:
        unpack: true
    - get: platform-automation-image
      params:
        unpack: true
    - get: pks-product
      trigger: true
      passed:
      - download-pks
    - get: configuration
      trigger: true
      passed:
      - download-pks
    - task: credhub-interpolate
      image: platform-automation-image
      file: platform-automation-tasks/tasks/credhub-interpolate.yml
      params:
        CREDHUB_CLIENT: ((credhub-client))
        CREDHUB_SECRET: ((credhub-secret))
        CREDHUB_SERVER: "https://credhub.control.fionathebluepittie.com:8844"
        CREDHUB_CA_CERT: ((lets_encrypt_cert.ca))
        PREFIX: /concourse/main/sandbox
        INTERPOLATION_PATHS: sandbox
      input_mapping:
        files: configuration
      output_mapping:
        interpolated-files: interpolated-config
    - task: upload-and-stage
      image: platform-automation-image
      file: platform-automation-tasks/tasks/upload-and-stage-product.yml
      params:
        ENV_FILE: sandbox/env.yml
      input_mapping:
        product: pks-product
        env: interpolated-config

- name: configure-pks
  plan:
    - get: platform-automation-tasks
      params:
        unpack: true
    - get: platform-automation-image
      params:
        unpack: true
    - get: configuration
      trigger: true
      passed:
      - upload-and-stage-pks
    - task: credhub-interpolate
      image: platform-automation-image
      file: platform-automation-tasks/tasks/credhub-interpolate.yml
      params:
        CREDHUB_CLIENT: ((credhub-client))
        CREDHUB_SECRET: ((credhub-secret))
        CREDHUB_SERVER: "https://credhub.control.fionathebluepittie.com:8844"
        CREDHUB_CA_CERT: ((lets_encrypt_cert.ca))
        PREFIX: /concourse/main/sandbox
        INTERPOLATION_PATHS: sandbox
      input_mapping:
        files: configuration
      output_mapping:
        interpolated-files: interpolated-config
    - task: configure
      image: platform-automation-image
      file: platform-automation-tasks/tasks/configure-product.yml
      params:
        ENV_FILE: sandbox/env.yml
        CONFIG_FILE: sandbox/install-pks/pks-config.yml
      input_mapping:
        env: interpolated-config
        config: interpolated-config

- name: apply-changes
  plan:
    - get: platform-automation-tasks
      params:
        unpack: true
    - get: platform-automation-image
      params:
        unpack: true
    - get: configuration
      passed:
      - configure-pks
    - task: credhub-interpolate
      image: platform-automation-image
      file: platform-automation-tasks/tasks/credhub-interpolate.yml
      params:
        CREDHUB_CLIENT: ((credhub-client))
        CREDHUB_SECRET: ((credhub-secret))
        CREDHUB_SERVER: "https://credhub.control.fionathebluepittie.com:8844"
        CREDHUB_CA_CERT: ((lets_encrypt_cert.ca))
        PREFIX: /concourse/main/sandbox
        INTERPOLATION_PATHS: sandbox
      input_mapping:
        files: configuration
      output_mapping:
        interpolated-files: interpolated-config
    - task: apply-changes
      image: platform-automation-image
      file: platform-automation-tasks/tasks/apply-changes.yml
      params:
        ENV_FILE: sandbox/env.yml
      input_mapping:
        env: interpolated-config