---
resources:
- name: configuration
  type: git
  source:
    uri: git@github.com:p-ssanders/simple-pipelines.git
    private_key: ((git-deploy-key.private_key))
    branch: master

- name: platform-automation-image
  type: s3
  source:
    access_key_id: ((access_key_id))
    secret_access_key: ((secret_access_key))
    region: us-east-1
    bucket: com.fionathebluepittie.sandbox
    regexp: platform-automation/platform-automation-image-(.*).tgz

- name: platform-automation-tasks
  type: s3
  source:
    access_key_id: ((access_key_id))
    secret_access_key: ((secret_access_key))
    region: us-east-1
    bucket: com.fionathebluepittie.sandbox
    regexp: platform-automation/platform-automation-tasks-(.*).zip

- name: compliance-scanner-product
  type: s3
  source:
    access_key_id: ((access_key_id))
    secret_access_key: ((secret_access_key))
    region: us-east-1
    bucket: com.fionathebluepittie.sandbox
    regexp: compliance-scanner/p-compliance-scanner-(.*).pivotal

- name: compliance-scanner-stemcell
  type: s3
  source:
    access_key_id: ((access_key_id))
    secret_access_key: ((secret_access_key))
    region: us-east-1
    bucket: com.fionathebluepittie.sandbox
    regexp: compliance-scanner/bosh-stemcell-(.*).tgz

jobs:
- name: download-compliance-scanner
  plan:
  - aggregate:
    - get: platform-automation-tasks
      params:
        unpack: true
    - get: platform-automation-image
      params:
        unpack: true
    - get: configuration
  - task: credhub-interpolate
    image: platform-automation-image
    file: platform-automation-tasks/tasks/credhub-interpolate.yml
    params:
      CREDHUB_CLIENT: ((credhub-client))
      CREDHUB_SECRET: ((credhub-secret))
      CREDHUB_SERVER: "https://credhub.control.fionathebluepittie.com:8844"
      CREDHUB_CA_CERT: ((lets_encrypt_cert.ca))
      PREFIX: /concourse/main/sandbox
      INTERPOLATION_PATHS: sandbox
    input_mapping:
      files: configuration
    output_mapping:
      interpolated-files: interpolated-config
  - task: download-compliance-scanner
    image: platform-automation-image
    file: platform-automation-tasks/tasks/download-product.yml
    params:
      CONFIG_FILE: sandbox/install-compliance-scanner/download-compliance-scanner.yml
    input_mapping:
      config: interpolated-config
    output_mapping:
      downloaded-stemcell: cs-stemcell
  - aggregate:
    - put: compliance-scanner-product
      params:
        file: downloaded-product/p-compliance-scanner-*.pivotal
    - put: compliance-scanner-stemcell
      params:
        file: cs-stemcell/*.tgz

- name: upload-and-stage-compliance-scanner
  plan:
  - aggregate:
    - get: configuration
    - get: platform-automation-tasks
      params:
        unpack: true
    - get: platform-automation-image
      params:
        unpack: true
    - get: compliance-scanner-product
      trigger: true
      passed:
      - download-compliance-scanner
  - task: credhub-interpolate
    image: platform-automation-image
    file: platform-automation-tasks/tasks/credhub-interpolate.yml
    params:
      CREDHUB_CLIENT: ((credhub-client))
      CREDHUB_SECRET: ((credhub-secret))
      CREDHUB_SERVER: "https://credhub.control.fionathebluepittie.com:8844"
      CREDHUB_CA_CERT: ((lets_encrypt_cert.ca))
      PREFIX: /concourse/main/sandbox
      INTERPOLATION_PATHS: sandbox
    input_mapping:
      files: configuration
    output_mapping:
      interpolated-files: interpolated-config
  - task: upload-stemcell
    image: platform-automation-image
    file: platform-automation-tasks/tasks/upload-stemcell.yml
    params:
      ENV_FILE: sandbox/env.yml
      CONFIG_FILE: sandbox/install-compliance-scanner/download-compliance-scanner.yml
    input_mapping:
      env: interpolated-config
      stemcell: compliance-scanner-stemcell
  - task: upload-and-stage
    image: platform-automation-image
    file: platform-automation-tasks/tasks/upload-and-stage-product.yml
    params:
      ENV_FILE: sandbox/env.yml
    input_mapping:
      product: compliance-scanner-product
      env: interpolated-config
# - name: configure-compliance-scanner
# - name: apply-changes
# - name: backup-compliance-scanner
# - name: run-scan