---
resources:
- name: configuration
  type: git
  source:
    uri: git@github.com:p-ssanders/simple-pipelines.git
    private_key: ((git-deploy-key.private_key))
    branch: master

- name: platform-automation-image
  type: s3
  source:
    access_key_id: ((access_key_id))
    secret_access_key: ((secret_access_key))
    region: us-east-1
    bucket: com.fionathebluepittie.sandbox
    regexp: platform-automation/platform-automation-image-(.*).tgz

- name: platform-automation-tasks
  type: s3
  source:
    access_key_id: ((access_key_id))
    secret_access_key: ((secret_access_key))
    region: us-east-1
    bucket: com.fionathebluepittie.sandbox
    regexp: platform-automation/platform-automation-tasks-(.*).zip

- name: compliance-scanner-product
  type: s3
  source:
    access_key_id: ((access_key_id))
    secret_access_key: ((secret_access_key))
    region: us-east-1
    bucket: com.fionathebluepittie.sandbox
    regexp: compliance-scanner/p-compliance-scanner-(.*).pivotal

- name: compliance-scanner-stemcell
  type: s3
  source:
    access_key_id: ((access_key_id))
    secret_access_key: ((secret_access_key))
    region: us-east-1
    bucket: com.fionathebluepittie.sandbox
    regexp: compliance-scanner/(.*)-stemcell-(.*).tgz

- name: compliance-scanner-backup
  type: s3
  source:
    access_key_id: ((access_key_id))
    secret_access_key: ((secret_access_key))
    region: us-east-1
    bucket: com.fionathebluepittie.sandbox
    versioned_file: compliance-scanner/backups/p-compliance-scanner.yml


jobs:
- name: download-compliance-scanner
  plan:
  - aggregate:
    - get: platform-automation-tasks
      params:
        unpack: true
    - get: platform-automation-image
      params:
        unpack: true
    - get: configuration
  - task: credhub-interpolate
    image: platform-automation-image
    file: platform-automation-tasks/tasks/credhub-interpolate.yml
    input_mapping:
      files: configuration
    params:
      CREDHUB_CLIENT: ((credhub-client))
      CREDHUB_SECRET: ((credhub-secret))
      CREDHUB_SERVER: "https://credhub.control.fionathebluepittie.com:8844"
      CREDHUB_CA_CERT: ((lets_encrypt_cert.ca))
      PREFIX: /concourse/main/sandbox
      INTERPOLATION_PATHS: sandbox
    output_mapping:
      interpolated-files: interpolated-config
  - task: download-compliance-scanner
    image: platform-automation-image
    file: platform-automation-tasks/tasks/download-product.yml
    input_mapping:
      config: interpolated-config
    params:
      CONFIG_FILE: sandbox/install-compliance-scanner/download-compliance-scanner.yml
  - aggregate:
    - put: compliance-scanner-product
      params:
        file: downloaded-product/p-compliance-scanner-*.pivotal
    # - put: compliance-scanner-stemcell
    #   params:
    #     file: downloaded-stemcell/*.tgz
    # - put: compliance-scanner-stemcell-config
    #   params:
    #     file: assign-stemcell-config/*.yml
  - task: download-compliance-scanner-stemcell
    image: platform-automation-image
    file: platform-automation-tasks/tasks/download-product.yml
    input_mapping:
      config: interpolated-config
    params:
      CONFIG_FILE: sandbox/install-compliance-scanner/download-compliance-scanner-stemcell.yml
  - aggregate:
    - put: compliance-scanner-stemcell
      params:
        file: downloaded-product/*.tgz

- name: upload-and-stage-compliance-scanner
  plan:
  - aggregate:
    - get: configuration
    - get: platform-automation-tasks
      params:
        unpack: true
    - get: platform-automation-image
      params:
        unpack: true
    - get: compliance-scanner-product
      trigger: true
      passed:
      - download-compliance-scanner
    - get: compliance-scanner-stemcell
      trigger: true
      passed:
      - download-compliance-scanner
  - task: credhub-interpolate
    image: platform-automation-image
    file: platform-automation-tasks/tasks/credhub-interpolate.yml
    input_mapping:
      files: configuration
    output_mapping:
      interpolated-files: interpolated-config
    params:
      CREDHUB_CLIENT: ((credhub-client))
      CREDHUB_SECRET: ((credhub-secret))
      CREDHUB_SERVER: "https://credhub.control.fionathebluepittie.com:8844"
      CREDHUB_CA_CERT: ((lets_encrypt_cert.ca))
      PREFIX: /concourse/main/sandbox
      INTERPOLATION_PATHS: sandbox
  - task: upload-stemcell
    image: platform-automation-image
    file: platform-automation-tasks/tasks/upload-stemcell.yml
    input_mapping:
      env: interpolated-config
      stemcell: compliance-scanner-stemcell
    params:
      ENV_FILE: sandbox/env.yml
  - task: upload-and-stage
    image: platform-automation-image
    file: platform-automation-tasks/tasks/upload-and-stage-product.yml
    params:
      ENV_FILE: sandbox/env.yml
    input_mapping:
      product: compliance-scanner-product
      env: interpolated-config

- name: configure-compliance-scanner
  plan:
    - get: platform-automation-tasks
      params:
        unpack: true
    - get: platform-automation-image
      params:
        unpack: true
    - get: configuration
      trigger: true
      passed:
      - upload-and-stage-compliance-scanner
    - task: credhub-interpolate
      image: platform-automation-image
      file: platform-automation-tasks/tasks/credhub-interpolate.yml
      input_mapping:
        files: configuration
      output_mapping:
        interpolated-files: interpolated-config
      params:
        CREDHUB_CLIENT: ((credhub-client))
        CREDHUB_SECRET: ((credhub-secret))
        CREDHUB_SERVER: "https://credhub.control.fionathebluepittie.com:8844"
        CREDHUB_CA_CERT: ((lets_encrypt_cert.ca))
        PREFIX: /concourse/main/sandbox
        INTERPOLATION_PATHS: sandbox
    - task: configure
      image: platform-automation-image
      file: platform-automation-tasks/tasks/configure-product.yml
      input_mapping:
        env: interpolated-config
        config: interpolated-config
      params:
        ENV_FILE: sandbox/env.yml
        CONFIG_FILE: sandbox/install-compliance-scanner/compliance-scanner-config.yml

- name: apply-changes
  plan:
    - get: platform-automation-tasks
      params:
        unpack: true
    - get: platform-automation-image
      params:
        unpack: true
    - get: configuration
      passed:
      - configure-compliance-scanner
    - task: credhub-interpolate
      image: platform-automation-image
      file: platform-automation-tasks/tasks/credhub-interpolate.yml
      params:
        CREDHUB_CLIENT: ((credhub-client))
        CREDHUB_SECRET: ((credhub-secret))
        CREDHUB_SERVER: "https://credhub.control.fionathebluepittie.com:8844"
        CREDHUB_CA_CERT: ((lets_encrypt_cert.ca))
        PREFIX: /concourse/main/sandbox
        INTERPOLATION_PATHS: sandbox
      input_mapping:
        files: configuration
      output_mapping:
        interpolated-files: interpolated-config
    - task: apply-changes
      image: platform-automation-image
      file: platform-automation-tasks/tasks/apply-changes.yml
      params:
        ENV_FILE: sandbox/env.yml
      input_mapping:
        env: interpolated-config

- name: backup-compliance-scanner
  plan:
    - aggregate:
      - get: platform-automation-tasks
        params:
          unpack: true
      - get: platform-automation-image
        params:
          unpack: true
      - get: configuration
        passed:
        - apply-changes
        trigger: true
    - task: credhub-interpolate
      image: platform-automation-image
      file: platform-automation-tasks/tasks/credhub-interpolate.yml
      params:
        CREDHUB_CLIENT: ((credhub-client))
        CREDHUB_SECRET: ((credhub-secret))
        CREDHUB_SERVER: "https://credhub.control.fionathebluepittie.com:8844"
        CREDHUB_CA_CERT: ((lets_encrypt_cert.ca))
        PREFIX: /concourse/main/sandbox
        INTERPOLATION_PATHS: sandbox
      input_mapping:
        files: configuration
      output_mapping:
        interpolated-files: interpolated-config
    - task: backup-compliance-scanner
      image: platform-automation-image
      file: platform-automation-tasks/tasks/staged-config.yml
      input_mapping:
        env: interpolated-config
      params:
        PRODUCT_NAME: p-compliance-scanner
        ENV_FILE: sandbox/env.yml
    - put: compliance-scanner-backup
      params:
        file: generated-config/*
# - name: run-scan